/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectosa;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import static proyectosa.Conexion.llenar_pendientes;
import static proyectosa.principal.pendientes;

/**
 *
 * @author Luis Diaz
 */
public class recursos extends javax.swing.JFrame {

    /**
     * Creates new form recursos
     */
    public recursos() {
        initComponents();
//        broncE.setVisible(false);
        platA.setVisible(false);
        orO.setVisible(false);
        platinuM.setVisible(false);
        
//        broncefoto.setVisible(false);
//        broncevideo.setVisible(false);
//        
//        platafoto.setVisible(false);
//        platavideo.setVisible(false);
//        
//        orofoto.setVisible(false);
//        orovideo.setVisible(false);
//        
//        plafoto.setVisible(false);
//        plavideo.setVisible(false);
        modelo.addColumn("Artículo");
        modelo.addColumn("Monto");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paquetes = new javax.swing.ButtonGroup();
        componentes = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        bronce = new javax.swing.JRadioButton();
        plata = new javax.swing.JRadioButton();
        oro = new javax.swing.JRadioButton();
        platinum = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        broncE = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        todobronce = new javax.swing.JRadioButton();
        broncefoto = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        f1 = new javax.swing.JRadioButton();
        f2 = new javax.swing.JRadioButton();
        broncevideo = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        v1 = new javax.swing.JRadioButton();
        v2 = new javax.swing.JRadioButton();
        platA = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        todoplata = new javax.swing.JRadioButton();
        platafoto = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        pf1 = new javax.swing.JRadioButton();
        pf2 = new javax.swing.JRadioButton();
        pf3 = new javax.swing.JRadioButton();
        platavideo = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        pv1 = new javax.swing.JRadioButton();
        pv2 = new javax.swing.JRadioButton();
        platinuM = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        todoplatinum = new javax.swing.JRadioButton();
        plafoto = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        plf1 = new javax.swing.JRadioButton();
        plf2 = new javax.swing.JRadioButton();
        plf3 = new javax.swing.JRadioButton();
        plavideo = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        plc1 = new javax.swing.JRadioButton();
        plc2 = new javax.swing.JRadioButton();
        plc3 = new javax.swing.JRadioButton();
        orO = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        todooro = new javax.swing.JRadioButton();
        orofoto = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        of1 = new javax.swing.JRadioButton();
        of2 = new javax.swing.JRadioButton();
        of3 = new javax.swing.JRadioButton();
        orovideo = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        ov1 = new javax.swing.JRadioButton();
        ov2 = new javax.swing.JRadioButton();
        ov3 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        total = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tota = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        o1 = new javax.swing.JRadioButton();
        o2 = new javax.swing.JRadioButton();
        o3 = new javax.swing.JRadioButton();
        o4 = new javax.swing.JRadioButton();
        o5 = new javax.swing.JRadioButton();
        o6 = new javax.swing.JRadioButton();
        o7 = new javax.swing.JRadioButton();
        o8 = new javax.swing.JRadioButton();
        o9 = new javax.swing.JRadioButton();
        o10 = new javax.swing.JRadioButton();
        o11 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectosa/BRONCE-2.png"))); // NOI18N
        jScrollPane3.setViewportView(jLabel4);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectosa/BRONCE-3.png"))); // NOI18N
        jScrollPane4.setViewportView(jLabel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Bronce", jPanel2);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectosa/PLATA-2.png"))); // NOI18N
        jScrollPane2.setViewportView(jLabel6);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectosa/PLATA-3.png"))); // NOI18N
        jScrollPane5.setViewportView(jLabel7);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Plata", jPanel3);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectosa/ORO-2.png"))); // NOI18N
        jScrollPane6.setViewportView(jLabel8);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectosa/ORO-3.png"))); // NOI18N
        jScrollPane7.setViewportView(jLabel9);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Oro", jPanel4);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectosa/PLATINUM-2.png"))); // NOI18N
        jScrollPane8.setViewportView(jLabel10);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectosa/PLATINUM-3.png"))); // NOI18N
        jScrollPane9.setViewportView(jLabel11);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Platinum", jPanel5);

        jLabel12.setText("Paquete:");

        paquetes.add(bronce);
        bronce.setText("Bronce");
        bronce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bronceMouseClicked(evt);
            }
        });

        paquetes.add(plata);
        plata.setText("Plata");
        plata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plataMouseClicked(evt);
            }
        });

        paquetes.add(oro);
        oro.setText("Oro");
        oro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oroMouseClicked(evt);
            }
        });

        paquetes.add(platinum);
        platinum.setText("Platinum");
        platinum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                platinumMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Bronce");

        todobronce.setText("Todo");

        jLabel15.setText("Fotografía");

        f1.setText("Save The Date");
        f1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f1MouseClicked(evt);
            }
        });

        f2.setText("Sesión día del evento");

        javax.swing.GroupLayout broncefotoLayout = new javax.swing.GroupLayout(broncefoto);
        broncefoto.setLayout(broncefotoLayout);
        broncefotoLayout.setHorizontalGroup(
            broncefotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
            .addGroup(broncefotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(broncefotoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(broncefotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(broncefotoLayout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(jLabel15)
                            .addGap(53, 53, 53))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, broncefotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f1)
                            .addComponent(f2)))
                    .addContainerGap(7, Short.MAX_VALUE)))
        );
        broncefotoLayout.setVerticalGroup(
            broncefotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(broncefotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(broncefotoLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jLabel15)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(f1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(f2)
                    .addContainerGap(27, Short.MAX_VALUE)))
        );

        jLabel16.setText("Video");

        v1.setText("Ceremonia religiosa");

        v2.setText("Recepción");

        javax.swing.GroupLayout broncevideoLayout = new javax.swing.GroupLayout(broncevideo);
        broncevideo.setLayout(broncevideoLayout);
        broncevideoLayout.setHorizontalGroup(
            broncevideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
            .addGroup(broncevideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(broncevideoLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(broncevideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(broncevideoLayout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addComponent(jLabel16)
                            .addGap(51, 51, 51))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, broncevideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(v2)
                            .addComponent(v1)))
                    .addContainerGap(11, Short.MAX_VALUE)))
        );
        broncevideoLayout.setVerticalGroup(
            broncevideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(broncevideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(broncevideoLayout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel16)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(v1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(v2)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout broncELayout = new javax.swing.GroupLayout(broncE);
        broncE.setLayout(broncELayout);
        broncELayout.setHorizontalGroup(
            broncELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(broncELayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(broncELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(broncELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(broncELayout.createSequentialGroup()
                        .addComponent(broncefoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(broncevideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(todobronce))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        broncELayout.setVerticalGroup(
            broncELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(broncELayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGroup(broncELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(broncELayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(broncefoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(broncELayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(broncevideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(todobronce))
        );

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("Plata");

        todoplata.setText("Todo");

        jLabel18.setText("Fotografía");

        pf1.setText("Save The Date");

        pf2.setText("Sesión día del evento");

        pf3.setText("Fotolibro digital");

        javax.swing.GroupLayout platafotoLayout = new javax.swing.GroupLayout(platafoto);
        platafoto.setLayout(platafotoLayout);
        platafotoLayout.setHorizontalGroup(
            platafotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 177, Short.MAX_VALUE)
            .addGroup(platafotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(platafotoLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(platafotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, platafotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pf1)
                            .addComponent(pf2))
                        .addGroup(platafotoLayout.createSequentialGroup()
                            .addGroup(platafotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(platafotoLayout.createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addComponent(jLabel18))
                                .addComponent(pf3))
                            .addGap(34, 34, 34)))
                    .addContainerGap(13, Short.MAX_VALUE)))
        );
        platafotoLayout.setVerticalGroup(
            platafotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
            .addGroup(platafotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(platafotoLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jLabel18)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(pf1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(pf2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(pf3)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel19.setText("Video");

        pv1.setText("Ceremonia religiosa");

        pv2.setText("Recepción");

        javax.swing.GroupLayout platavideoLayout = new javax.swing.GroupLayout(platavideo);
        platavideo.setLayout(platavideoLayout);
        platavideoLayout.setHorizontalGroup(
            platavideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(platavideoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(platavideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(platavideoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(platavideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, platavideoLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(59, 59, 59))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, platavideoLayout.createSequentialGroup()
                                .addComponent(pv1)
                                .addContainerGap())))
                    .addGroup(platavideoLayout.createSequentialGroup()
                        .addComponent(pv2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        platavideoLayout.setVerticalGroup(
            platavideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(platavideoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pv1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pv2)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout platALayout = new javax.swing.GroupLayout(platA);
        platA.setLayout(platALayout);
        platALayout.setHorizontalGroup(
            platALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(platALayout.createSequentialGroup()
                .addGroup(platALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(platALayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(platafoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(platavideo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17))
                .addGap(375, 375, 375))
            .addGroup(platALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(todoplata)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        platALayout.setVerticalGroup(
            platALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(platALayout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(12, 12, 12)
                .addGroup(platALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(platafoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(platavideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(todoplata))
        );

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setText("Platinum");

        todoplatinum.setText("Todo");

        jLabel24.setText("Fotografía");

        plf1.setText("Save The Date");

        plf2.setText("Trash The Dress");

        plf3.setText("Fotolibro");

        javax.swing.GroupLayout plafotoLayout = new javax.swing.GroupLayout(plafoto);
        plafoto.setLayout(plafotoLayout);
        plafotoLayout.setHorizontalGroup(
            plafotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plafotoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel24)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plafotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(plf1)
                .addComponent(plf2)
                .addComponent(plf3))
        );
        plafotoLayout.setVerticalGroup(
            plafotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plafotoLayout.createSequentialGroup()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plf1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plf2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plf3))
        );

        jLabel25.setText("Cortomeraje");

        plc1.setText("Wedding Short Film");

        plc2.setText("Wedding Trailer");

        plc3.setText("Drone 4K");

        javax.swing.GroupLayout plavideoLayout = new javax.swing.GroupLayout(plavideo);
        plavideo.setLayout(plavideoLayout);
        plavideoLayout.setHorizontalGroup(
            plavideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plavideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(plc3)
                .addComponent(plc2)
                .addComponent(plc1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plavideoLayout.createSequentialGroup()
                .addComponent(jLabel25)
                .addGap(32, 32, 32))
        );
        plavideoLayout.setVerticalGroup(
            plavideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plavideoLayout.createSequentialGroup()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plc1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plc2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plc3))
        );

        javax.swing.GroupLayout platinuMLayout = new javax.swing.GroupLayout(platinuM);
        platinuM.setLayout(platinuMLayout);
        platinuMLayout.setHorizontalGroup(
            platinuMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(platinuMLayout.createSequentialGroup()
                .addComponent(jLabel23)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(platinuMLayout.createSequentialGroup()
                .addGroup(platinuMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(todoplatinum)
                    .addGroup(platinuMLayout.createSequentialGroup()
                        .addComponent(plafoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plavideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        platinuMLayout.setVerticalGroup(
            platinuMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(platinuMLayout.createSequentialGroup()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(platinuMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plafoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plavideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(todoplatinum))
        );

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setText("Oro");

        todooro.setText("Todo");

        jLabel21.setText("Fotografía");

        of1.setText("Save The Date");

        of2.setText("Sesión día del evento");

        of3.setText("Fotolibro ");

        javax.swing.GroupLayout orofotoLayout = new javax.swing.GroupLayout(orofoto);
        orofoto.setLayout(orofotoLayout);
        orofotoLayout.setHorizontalGroup(
            orofotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orofotoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel21)
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orofotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(of1)
                .addComponent(of2)
                .addComponent(of3))
        );
        orofotoLayout.setVerticalGroup(
            orofotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orofotoLayout.createSequentialGroup()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(of1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(of2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(of3))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        jLabel22.setText("Video");

        ov1.setText("Getting ready");

        ov2.setText("Ceremonia religiosa");

        ov3.setText("Recepción");

        javax.swing.GroupLayout orovideoLayout = new javax.swing.GroupLayout(orovideo);
        orovideo.setLayout(orovideoLayout);
        orovideoLayout.setHorizontalGroup(
            orovideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orovideoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(orovideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orovideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ov3)
                        .addComponent(ov2)
                        .addComponent(ov1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orovideoLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(51, 51, 51)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        orovideoLayout.setVerticalGroup(
            orovideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orovideoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(orovideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orovideoLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ov1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ov2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ov3))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout orOLayout = new javax.swing.GroupLayout(orO);
        orO.setLayout(orOLayout);
        orOLayout.setHorizontalGroup(
            orOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orOLayout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(orOLayout.createSequentialGroup()
                .addGroup(orOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(todooro)
                    .addComponent(orofoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orovideo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        orOLayout.setVerticalGroup(
            orOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orOLayout.createSequentialGroup()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(orOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orofoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orovideo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(todooro))
        );

        total.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Artículo", "Monto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(total);

        jLabel1.setText("TOTAL:");

        jLabel2.setText("$");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tota, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText("Total:");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        o1.setText("Save The Date");
        o1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                o1MouseClicked(evt);
            }
        });

        o2.setText("Sesión día del evento");

        o3.setText("Ceremonia religiosa");

        o4.setText("Recepción");

        o5.setText("Fotolibro ");

        o6.setText("Fotolibro digital");

        o7.setText("Getting ready");

        o8.setText("Trash The Dress");

        o9.setText("Wedding Short Film");

        o10.setText("Wedding Trailer");

        o11.setText("Drone 4K");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(o1)
                    .addComponent(o11))
                .addGap(11, 11, 11)
                .addComponent(o2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(o3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(o4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(o5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(o6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(o7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(o8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(o9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(o10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(o5)
                    .addComponent(o6)
                    .addComponent(o4)
                    .addComponent(o3)
                    .addComponent(o2)
                    .addComponent(o1)
                    .addComponent(o7)
                    .addComponent(o8)
                    .addComponent(o9)
                    .addComponent(o10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(o11))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(67, 67, 67))
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel12))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bronce)
                                        .addGap(18, 18, 18)
                                        .addComponent(plata)
                                        .addGap(18, 18, 18)
                                        .addComponent(oro)
                                        .addGap(18, 18, 18)
                                        .addComponent(platinum))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(broncE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(platA, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(orO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(platinuM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bronce)
                    .addComponent(plata)
                    .addComponent(oro)
                    .addComponent(platinum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(platA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(broncE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(platinuM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Generador", jPanel1);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Recursos");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectosa/cancel.png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(657, 657, 657)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1712, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bronceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bronceMouseClicked
        // TODO add your handling code here:
        if(bronce.isSelected()){
        broncE.setVisible(true);
        platA.setVisible(false);
        orO.setVisible(false);
        platinuM.setVisible(false);
        }else{
            broncE.setVisible(false);
        }
    }//GEN-LAST:event_bronceMouseClicked

    private void plataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plataMouseClicked
        // TODO add your handling code here:
        if(plata.isSelected()){
        platA.setVisible(true);
        orO.setVisible(false);
        platinuM.setVisible(false);
        broncE.setVisible(false);
        }else{
            platA.setVisible(false);
        }
    }//GEN-LAST:event_plataMouseClicked

    private void oroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oroMouseClicked
        // TODO add your handling code here:
        if(oro.isSelected()){
        orO.setVisible(true);
        platinuM.setVisible(false);
        platA.setVisible(false);
        broncE.setVisible(false);
        }else{
            orO.setVisible(false);
        }
    }//GEN-LAST:event_oroMouseClicked

    private void platinumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_platinumMouseClicked
        // TODO add your handling code here:
        if(platinum.isSelected()){
            platinuM.setVisible(true);
            broncE.setVisible(false);
            platA.setVisible(false);
            orO.setVisible(false);
        }else{
            platinuM.setVisible(false);
        }
    }//GEN-LAST:event_platinumMouseClicked
Object [] fila=new Object[2]; 
Object [] fila2=new Object[2]; 
Object [] fila3=new Object[2]; 
Object [] fila4=new Object[2]; 
Object [] fila5=new Object[2]; 
Object [] fila6=new Object[2]; 

Object [] fi1=new Object[2]; 
Object [] fi2=new Object[2]; 
Object [] fi3=new Object[2]; 
Object [] fi4=new Object[2]; 
Object [] fi5=new Object[2]; 
Object [] fi6=new Object[2]; 
Object [] fi7=new Object[2]; 
Object [] fi8=new Object[2]; 
Object [] fi9=new Object[2]; 
Object [] fi10=new Object[2]; 
Object [] fi11=new Object[2]; 

int [] to=new int[10]; 
DefaultTableModel modelo = new DefaultTableModel();
public void eliminar(){
        DefaultTableModel tb = (DefaultTableModel) total.getModel();
        int a = total.getRowCount()-1;
        int b= total.getColumnCount()-1;
        for (int i = a; i >= 0; i--) {           
        tb.removeRow(tb.getRowCount()-1);
        } 
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        eliminar();
        fila[0]="Save the date"; 
        fila[1]="4000"; 
        fila2[0]="Sesión día del evento"; 
        fila2[1]="4000"; 
        fila3[0]="Ceremonia religiosa"; 
        fila3[1]="4000"; 
        fila4[0]="Recepción"; 
        fila4[1]="4000"; 
        
        fila5[0]="Fotolibro digital"; 
        fila5[1]="3500"; 
                
        
        fi1[0]="Save the Date";
        fi1[1]="5400";
        
        fi2[0]="Sesión día del evento";
        fi2[1]="7000";
        
        fi3[0]="Ceremonia religiosa";
        fi3[1]="6830";
        
        fi4[0]="Recepción";
        fi4[1]="4300";
        
        fi5[0]="Fotolibro";
        fi5[1]="5600";
        
        fi6[0]="Fotolibro digital";
        fi6[1]="4100";
        
        fi7[0]="Gettin Ready";
        fi7[1]="4700";
        
        fi8[0]="Trash The Dress";
        fi8[1]="8300";
        
        fi9[0]="Wedding Short Film";
        fi9[1]="7800";
        
        fi10[0]="Wedding Trailer";
        fi10[1]="7800";
        
        fi11[0]="Drone 4K";
        fi11[1]="8000";
        
        
        
//        if(!bronce.isSelected() || !oro.isSelected() || !plata.isSelected() || !platinum.isSelected()){
                if(o1.isSelected()){
                    modelo.addRow(fi1); 
                }
                if(o2.isSelected()){
                    modelo.addRow(fi2); 
                }
                if(o3.isSelected()){
                    modelo.addRow(fi3); 
                }
                if(o4.isSelected()){
                    modelo.addRow(fi4); 
                }
                if(o5.isSelected()){
                    modelo.addRow(fi5); 
                }
                if(o6.isSelected()){
                    modelo.addRow(fi6); 
                }
                if(o7.isSelected()){
                    modelo.addRow(fi7); 
                }
                if(o8.isSelected()){
                    modelo.addRow(fi8); 
                }
                if(o9.isSelected()){
                    modelo.addRow(fi9); 
                }
                if(o10.isSelected()){
                    modelo.addRow(fi10); 
                }
                if(o11.isSelected()){
                    modelo.addRow(fi11); 
                }
//        }
        
        
        if(bronce.isSelected()){
            if(f1.isSelected()){
                modelo.addRow(fila); 
            }
            if(f2.isSelected()){
                modelo.addRow(fila2); 
            }
            if(v1.isSelected()){
                modelo.addRow(fila3); 
            }
            if(v2.isSelected()){
                modelo.addRow(fila4); 
            }
            if(todobronce.isSelected()){
                eliminar();
                modelo.addRow(fila);
                modelo.addRow(fila2);
                modelo.addRow(fila3);
                modelo.addRow(fila4);
            }
        }
        
        if(plata.isSelected()){
            fila[1]="3500"; 
            fila2[1]="3500"; 
            fila3[1]="5250"; 
            fila4[1]="5250"; 
            if(pf1.isSelected()){
                
                modelo.addRow(fila); 
            }
            if(pf2.isSelected()){
                
                modelo.addRow(fila2); 
            }
            if(pf3.isSelected()){
                
                modelo.addRow(fila5); 
            }
            
            if(pv1.isSelected()){
                
                modelo.addRow(fila3); 
            }
            if(pv2.isSelected()){
                
                modelo.addRow(fila4); 
            }
            if(todoplata.isSelected()){
                eliminar();
                modelo.addRow(fila);
                modelo.addRow(fila2);
                modelo.addRow(fila3);
                modelo.addRow(fila4);
                modelo.addRow(fila5);
            }
        }
        
        
        if(oro.isSelected()){
            fila[1]="4416"; 
            fila2[1]="4416"; 
            fila5[1]="4416";
            fila3[0]="Getting Ready"; 
                fila3[1]="4416"; 
                fila4[0]="Ceremonia religiosa";  
                fila4[1]="4416"; 
                fila6[0]="Recepción"; 
                fila6[1]="4416"; 
                
            if(of1.isSelected()){
                
                modelo.addRow(fila); 
            }
            if(of2.isSelected()){
                
                modelo.addRow(fila2); 
            }
            if(of3.isSelected()){
                
                modelo.addRow(fila5); 
            }
            
            if(ov1.isSelected()){
                
                modelo.addRow(fila3); 
            }
            if(ov2.isSelected()){
                
                modelo.addRow(fila4); 
            }
            if(ov3.isSelected()){
                
                modelo.addRow(fila6); 
            }
            if(todooro.isSelected()){
                eliminar();
                modelo.addRow(fila);
                modelo.addRow(fila2);
                modelo.addRow(fila5);
                modelo.addRow(fila3);
                modelo.addRow(fila4);
                modelo.addRow(fila6);
            }
        }
        
        if(platinum.isSelected()){
            fila[0]="Save the date"; 
                fila[1]="7500";
                fila2[1]="Trash The Dress"; 
                fila2[1]="7500"; 
                fila5[1]="Fotolibro"; 
                fila5[1]="7500"; 
                fila3[0]="Wedding Short Film"; 
                fila3[1]="7500"; 
                fila4[0]="Wedding Trailer";  
                fila4[1]="7500"; 
                fila6[0]="Drone 4K"; 
                fila6[1]="7500"; 
            if(plf1.isSelected()){
                modelo.addRow(fila); 
            }
            if(plf2.isSelected()){
                
                modelo.addRow(fila2); 
            }
            if(plf3.isSelected()){
                
                modelo.addRow(fila5); 
            }
            
            if(plc1.isSelected()){
                
                modelo.addRow(fila3); 
            }
            if(plc2.isSelected()){
                
                modelo.addRow(fila4); 
            }
            if(plc3.isSelected()){
                
                modelo.addRow(fila6); 
            }
            if(todoplatinum.isSelected()){
                eliminar();
                modelo.addRow(fila);
                modelo.addRow(fila2);
                modelo.addRow(fila5);
                modelo.addRow(fila3);
                modelo.addRow(fila4);
                modelo.addRow(fila6);
            }
        }
        int i;
        String valor;
        int fila = total.getRowCount();
        for (i = 0; i < 10; i++) {
            to[i]=0;
        }
        
        for (i = 0; i < fila; i++) {
            valor = (String) total.getValueAt(i, 1);
            to[i]=Integer.parseInt(valor);
        }
//        String valores = valor + ", ";
//        JOptionPane.showMessageDialog(null, "valores de la columna1: " + valores);
        int up = 0;
        for(int r=0;r<10;r++){
            up=up+to[r];
        }
        
        String h=Integer.toString(up);
        tota.setText(h);
        total.setModel(modelo); 
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void f1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_f1MouseClicked

    private void o1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_o1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_o1MouseClicked

    /**
     * @param args the command line arguments
     */
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
        getImage(ClassLoader.getSystemResource("proyectosa/badge.png"));


        return retValue;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel broncE;
    private javax.swing.JRadioButton bronce;
    private javax.swing.JPanel broncefoto;
    private javax.swing.JPanel broncevideo;
    private javax.swing.ButtonGroup componentes;
    private javax.swing.JRadioButton f1;
    private javax.swing.JRadioButton f2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton o1;
    private javax.swing.JRadioButton o10;
    private javax.swing.JRadioButton o11;
    private javax.swing.JRadioButton o2;
    private javax.swing.JRadioButton o3;
    private javax.swing.JRadioButton o4;
    private javax.swing.JRadioButton o5;
    private javax.swing.JRadioButton o6;
    private javax.swing.JRadioButton o7;
    private javax.swing.JRadioButton o8;
    private javax.swing.JRadioButton o9;
    private javax.swing.JRadioButton of1;
    private javax.swing.JRadioButton of2;
    private javax.swing.JRadioButton of3;
    private javax.swing.JPanel orO;
    private javax.swing.JRadioButton oro;
    private javax.swing.JPanel orofoto;
    private javax.swing.JPanel orovideo;
    private javax.swing.JRadioButton ov1;
    private javax.swing.JRadioButton ov2;
    private javax.swing.JRadioButton ov3;
    private javax.swing.ButtonGroup paquetes;
    private javax.swing.JRadioButton pf1;
    private javax.swing.JRadioButton pf2;
    private javax.swing.JRadioButton pf3;
    private javax.swing.JPanel plafoto;
    private javax.swing.JPanel platA;
    private javax.swing.JRadioButton plata;
    private javax.swing.JPanel platafoto;
    private javax.swing.JPanel platavideo;
    private javax.swing.JPanel platinuM;
    private javax.swing.JRadioButton platinum;
    private javax.swing.JPanel plavideo;
    private javax.swing.JRadioButton plc1;
    private javax.swing.JRadioButton plc2;
    private javax.swing.JRadioButton plc3;
    private javax.swing.JRadioButton plf1;
    private javax.swing.JRadioButton plf2;
    private javax.swing.JRadioButton plf3;
    private javax.swing.JRadioButton pv1;
    private javax.swing.JRadioButton pv2;
    private javax.swing.JRadioButton todobronce;
    private javax.swing.JRadioButton todooro;
    private javax.swing.JRadioButton todoplata;
    private javax.swing.JRadioButton todoplatinum;
    private javax.swing.JTextField tota;
    private javax.swing.JTable total;
    private javax.swing.JRadioButton v1;
    private javax.swing.JRadioButton v2;
    // End of variables declaration//GEN-END:variables
}
