/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectosa;

import ds.desktop.notify.DesktopNotify;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static proyectosa.Conexion.conectar;
import static proyectosa.Conexion.historial_cliente;

/**
 *
 * @author Luis Diaz
 */
public class registro_clientes extends javax.swing.JFrame {

    /**
     * Creates new form registro_clientes
     */
    
        static Connection conexion=null;
    static Statement sentencia;
    static ResultSet resultado;
    static ResultSetMetaData resultadometa;
    
    public registro_clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        comentarios = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(790, 450));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Registrar un nuevo cliente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 10, 188, 19);

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 50, 45, 16);

        jLabel3.setText("Teléfono");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 80, 49, 16);

        jLabel4.setText("Correo ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 110, 42, 16);

        jLabel5.setText("Comentarios");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 160, 73, 16);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectosa/floppy-disk.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(620, 340, 130, 48);
        getContentPane().add(nombre);
        nombre.setBounds(150, 40, 610, 24);

        telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoKeyTyped(evt);
            }
        });
        getContentPane().add(telefono);
        telefono.setBounds(150, 80, 610, 24);

        correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoActionPerformed(evt);
            }
        });
        getContentPane().add(correo);
        correo.setBounds(150, 120, 610, 24);

        comentarios.setColumns(20);
        comentarios.setRows(5);
        jScrollPane1.setViewportView(comentarios);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(150, 160, 610, 116);

        jLabel6.setText("electrónico");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 130, 64, 16);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectosa/rating.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 290, 70, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
        getImage(ClassLoader.getSystemResource("proyectosa/badge.png"));


        return retValue;
    }
    private void telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_telefonoKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        conectar();
        String n1=nombre.getText();
        String t1=telefono.getText();
        String co1=correo.getText();
        String c1=comentarios.getText();
        Connection cn=null;
        
        if( (n1.length()== 0)  ||  (t1.length()== 0) ||  (co1.length()== 0) ||  (c1.length()== 0)){
            JOptionPane.showMessageDialog(null,"Los campos no pueden estar vacíos", "Alerta",JOptionPane.WARNING_MESSAGE, new ImageIcon("C:\\Users\\Luis Diaz\\Documents\\NetBeansProjects\\ProyectoSA\\src\\proyectosa\\warning.png"));
        }else{
            try{
                Class.forName("com.mysql.jdbc.Driver");
                cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/asistente_ventas","root","344391");
                String n=nombre.getText();
                String t=telefono.getText();
                String co=correo.getText();
                String c=comentarios.getText();
                int usu=ProyectoSA.usuario_sesion;
                String query = "INSERT INTO clientes (nombre, telefono, corre_electronico, comentarios, creado_por) VALUES ('"+n+"', '"+t+"', '"+co+"', '"+c+"', "+usu+")";
                Statement stmt = cn.createStatement();
                stmt.executeUpdate(query);
                nombre.setText("");
                telefono.setText("");
                correo.setText("");
                comentarios.setText("");
                DesktopNotify.showDesktopMessage("Corecto", "El cliente fue agregado con éxito", DesktopNotify.SUCCESS, 7000L);
                historial_cliente(n);
            }catch(SQLException e){
                System.out.println("SQLException: " + e.getMessage());
                System.out.println("SQLState: "+e.getSQLState());
                System.out.println("vendorError: "+e.getErrorCode());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(registro_clientes.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro_clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea comentarios;
    private javax.swing.JTextField correo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
